[package]
name = "RustFetch"
version = "0.1.0"
edition = "2024"

[dependencies]
cliclack = "0.3.6"
serde = { version = "1.0.219", features = ["derive"] }
clap = { version = "4.5.40", features = ["derive"] }
serde_json = "1.0.140"